# Generated by Django 3.2.9 on 2021-11-03 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_url', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='long_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='short_link',
            new_name='new_link',
        ),
    ]
